// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDALV7H4D_cGQkIOBWE9LfJBgQS0EVNn9c',
    appId: '1:367479444306:web:c0d3eda5e67855be77a08b',
    messagingSenderId: '367479444306',
    projectId: 'test-ticket-ca5b1',
    authDomain: 'test-ticket-ca5b1.firebaseapp.com',
    storageBucket: 'test-ticket-ca5b1.firebasestorage.app',
    measurementId: 'G-LY9TNNKZ4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8RK70_pUoRiZ9N_H5lopvdvAhg9-EWic',
    appId: '1:367479444306:android:c28c732621f3054477a08b',
    messagingSenderId: '367479444306',
    projectId: 'test-ticket-ca5b1',
    storageBucket: 'test-ticket-ca5b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ6-499LEpMP7p1GMeT5K0WwSetbTZPxo',
    appId: '1:367479444306:ios:55f1b0de7c1e174177a08b',
    messagingSenderId: '367479444306',
    projectId: 'test-ticket-ca5b1',
    storageBucket: 'test-ticket-ca5b1.firebasestorage.app',
    iosBundleId: 'com.example.testTicket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ6-499LEpMP7p1GMeT5K0WwSetbTZPxo',
    appId: '1:367479444306:ios:55f1b0de7c1e174177a08b',
    messagingSenderId: '367479444306',
    projectId: 'test-ticket-ca5b1',
    storageBucket: 'test-ticket-ca5b1.firebasestorage.app',
    iosBundleId: 'com.example.testTicket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDALV7H4D_cGQkIOBWE9LfJBgQS0EVNn9c',
    appId: '1:367479444306:web:626715eb7a3d094577a08b',
    messagingSenderId: '367479444306',
    projectId: 'test-ticket-ca5b1',
    authDomain: 'test-ticket-ca5b1.firebaseapp.com',
    storageBucket: 'test-ticket-ca5b1.firebasestorage.app',
    measurementId: 'G-1FBKQX425S',
  );
}
